# services:
#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: n8n
#       POSTGRES_PASSWORD: n8n
#       POSTGRES_DB: n8n
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   n8n:
#     image: n8nio/n8n
#     ports:
#       - "5678:5678"
#     environment:
#       DB_TYPE: postgresdb
#       DB_POSTGRESDB_HOST: postgres
#       DB_POSTGRESDB_PORT: 5432
#       DB_POSTGRESDB_DATABASE: n8n
#       DB_POSTGRESDB_USER: n8n
#       DB_POSTGRESDB_PASSWORD: n8n
#     depends_on:
#       - postgres

# volumes:
#   postgres:

version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
    depends_on:
      - postgres
    volumes:
      - ./dist/nodes:/home/node/.n8n/custom   # Monta seus nós personalizados
      - n8n_data:/home/node/.n8n               # Persiste dados do n8n
      - ./icons:home/node/.n8n/icons

volumes:
  postgres_data:
  n8n_data:
